/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReferenciasRouteImport } from './routes/referencias'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as CriativosRouteImport } from './routes/criativos'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as IndexRouteImport } from './routes/index'

const ReferenciasRoute = ReferenciasRouteImport.update({
  id: '/referencias',
  path: '/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const CriativosRoute = CriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/criativos': typeof CriativosRoute
  '/metas': typeof MetasRoute
  '/projetos': typeof ProjetosRoute
  '/referencias': typeof ReferenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/criativos': typeof CriativosRoute
  '/metas': typeof MetasRoute
  '/projetos': typeof ProjetosRoute
  '/referencias': typeof ReferenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conteudos': typeof ConteudosRoute
  '/criativos': typeof CriativosRoute
  '/metas': typeof MetasRoute
  '/projetos': typeof ProjetosRoute
  '/referencias': typeof ReferenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conteudos'
    | '/criativos'
    | '/metas'
    | '/projetos'
    | '/referencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conteudos'
    | '/criativos'
    | '/metas'
    | '/projetos'
    | '/referencias'
  id:
    | '__root__'
    | '/'
    | '/conteudos'
    | '/criativos'
    | '/metas'
    | '/projetos'
    | '/referencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConteudosRoute: typeof ConteudosRoute
  CriativosRoute: typeof CriativosRoute
  MetasRoute: typeof MetasRoute
  ProjetosRoute: typeof ProjetosRoute
  ReferenciasRoute: typeof ReferenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/referencias': {
      id: '/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof ReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criativos': {
      id: '/criativos'
      path: '/criativos'
      fullPath: '/criativos'
      preLoaderRoute: typeof CriativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConteudosRoute: ConteudosRoute,
  CriativosRoute: CriativosRoute,
  MetasRoute: MetasRoute,
  ProjetosRoute: ProjetosRoute,
  ReferenciasRoute: ReferenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
